#!/usr/bin/env bun
import { mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";

const ROOT = dirname(new URL(import.meta.url).pathname);
const DIST = join(ROOT, "dist");
const SRC = join(ROOT, "tokens.json");

type Hex = `#${string}`;
type Tokens = {
  version: string;
  brand: Record<string, Hex>;
  semantic: { light: Record<string, Hex>; dark: Record<string, Hex> };
  type: {
    sans: string;
    serif: string;
    mono: string;
    scale: Record<string, string>;
    weight: Record<string, string>;
    lineHeight: Record<string, string>;
  };
  space: Record<string, string>;
  radius: Record<string, string>;
  shadow: Record<string, string>;
  container: Record<string, string>;
};

const tokens = JSON.parse(readFileSync(SRC, "utf8")) as Tokens;

mkdirSync(DIST, { recursive: true });

const banner = (kind: string) =>
  `/*!\n * @ua/ua-tokens · ${kind} · v${tokens.version}\n * GENERATED by packages/ua-tokens/build.ts — do not edit by hand.\n * Source of truth: packages/ua-tokens/tokens.json\n */\n`;

// ─── tokens.css ────────────────────────────────────────────────────────────
function emitCss() {
  const lines: string[] = [];
  lines.push(banner("CSS variables").replace("/*!", "/*"));
  lines.push(":root {");
  lines.push("  /* Brand tokens — canonical --ua-* */");
  for (const [name, hex] of Object.entries(tokens.brand)) {
    lines.push(`  --ua-${name}: ${hex};`);
  }
  lines.push("");
  lines.push("  /* Brand aliases — --az-* for bear-down-lms compatibility */");
  for (const name of Object.keys(tokens.brand)) {
    lines.push(`  --az-${name}: var(--ua-${name});`);
  }
  lines.push("");
  lines.push("  /* Semantic tokens — light theme (default) */");
  for (const [name, hex] of Object.entries(tokens.semantic.light)) {
    lines.push(`  --${name}: ${hex};`);
  }
  lines.push("");
  lines.push("  /* Typography */");
  lines.push(`  --font-sans: ${tokens.type.sans};`);
  lines.push(`  --font-serif: ${tokens.type.serif};`);
  lines.push(`  --font-mono: ${tokens.type.mono};`);
  for (const [k, v] of Object.entries(tokens.type.scale)) {
    lines.push(`  --font-size-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(tokens.type.weight)) {
    lines.push(`  --font-weight-${k}: ${v};`);
  }
  for (const [k, v] of Object.entries(tokens.type.lineHeight)) {
    lines.push(`  --line-height-${k}: ${v};`);
  }
  lines.push("");
  lines.push("  /* Space */");
  for (const [k, v] of Object.entries(tokens.space)) {
    lines.push(`  --space-${k}: ${v};`);
  }
  lines.push("");
  lines.push("  /* Radius */");
  for (const [k, v] of Object.entries(tokens.radius)) {
    lines.push(`  --radius-${k}: ${v};`);
  }
  lines.push("");
  lines.push("  /* Shadow */");
  for (const [k, v] of Object.entries(tokens.shadow)) {
    lines.push(`  --shadow-${k}: ${v};`);
  }
  lines.push("");
  lines.push("  /* Container */");
  for (const [k, v] of Object.entries(tokens.container)) {
    lines.push(`  --container-${k}: ${v};`);
  }
  lines.push("}");
  lines.push("");
  lines.push('[data-theme="dark"],');
  lines.push("[data-bs-theme=\"dark\"] {");
  lines.push("  /* Semantic tokens — dark theme (brand-true navy) */");
  for (const [name, hex] of Object.entries(tokens.semantic.dark)) {
    lines.push(`  --${name}: ${hex};`);
  }
  lines.push("  color-scheme: dark;");
  lines.push("}");
  lines.push("");
  writeFileSync(join(DIST, "tokens.css"), lines.join("\n"));
}

// ─── tokens.scss ───────────────────────────────────────────────────────────
function emitScss() {
  const lines: string[] = [];
  lines.push(banner("SCSS variables"));
  lines.push("// Brand variables — names match az-digital/arizona-bootstrap");
  for (const [name, hex] of Object.entries(tokens.brand)) {
    // Convert kebab-case keys to SCSS-friendly names
    const scssName = name.replace(/-/g, "-");
    lines.push(`$${scssName}: ${hex};`);
  }
  lines.push("");
  lines.push("// Common az-digital aliases");
  lines.push("$gray-100: #f8f9fa;");
  lines.push("$gray-200: #e9ecef;");
  lines.push("$gray-300: #dee2e6;");
  lines.push("$gray-400: #ced4da;");
  lines.push("$gray-500: #adb5bd;");
  lines.push("$gray-600: #6c757d;");
  lines.push("$gray-700: #495057;");
  lines.push("$gray-800: #343a40;");
  lines.push("$gray-900: #212529;");
  lines.push("");
  lines.push("// Semantic — light");
  for (const [name, hex] of Object.entries(tokens.semantic.light)) {
    lines.push(`$${name}-light: ${hex};`);
  }
  lines.push("");
  lines.push("// Semantic — dark");
  for (const [name, hex] of Object.entries(tokens.semantic.dark)) {
    lines.push(`$${name}-dark: ${hex};`);
  }
  lines.push("");
  writeFileSync(join(DIST, "tokens.scss"), lines.join("\n"));
}

// ─── tokens.ts (+ .js + .d.ts) ─────────────────────────────────────────────
function emitTs() {
  const body = `${banner("TypeScript object")}export const tokens = ${JSON.stringify(
    tokens,
    null,
    2,
  )} as const;\n\nexport type Tokens = typeof tokens;\nexport type BrandToken = keyof typeof tokens.brand;\nexport type SemanticToken = keyof typeof tokens.semantic.light;\n`;
  writeFileSync(join(DIST, "tokens.ts"), body);

  // Also emit .js + .d.ts so non-TS consumers (Node, CJS scripts) can require it
  const jsBody = `${banner("CommonJS export")}"use strict";\nObject.defineProperty(exports, "__esModule", { value: true });\nexports.tokens = ${JSON.stringify(
    tokens,
    null,
    2,
  )};\n`;
  writeFileSync(join(DIST, "tokens.cjs"), jsBody);

  const esmBody = `${banner("ESM export")}export const tokens = ${JSON.stringify(
    tokens,
    null,
    2,
  )};\n`;
  writeFileSync(join(DIST, "tokens.js"), esmBody);

  const dts = `${banner("TS type declarations")}export declare const tokens: ${JSON.stringify(
    tokens,
    null,
    2,
  )};\nexport type Tokens = typeof tokens;\nexport type BrandToken = keyof typeof tokens.brand;\nexport type SemanticToken = keyof typeof tokens.semantic.light;\n`;
  writeFileSync(join(DIST, "tokens.d.ts"), dts);
}

// ─── tailwind.preset.cjs ───────────────────────────────────────────────────
function emitTailwind() {
  const semantic = Object.fromEntries(
    Object.keys(tokens.semantic.light).map((name) => [name, `var(--${name})`]),
  );

  const preset = {
    theme: {
      extend: {
        colors: {
          ua: tokens.brand,
          semantic,
        },
        fontFamily: {
          sans: [tokens.type.sans],
          serif: [tokens.type.serif],
          mono: [tokens.type.mono],
        },
        fontSize: tokens.type.scale,
        fontWeight: tokens.type.weight,
        lineHeight: tokens.type.lineHeight,
        spacing: tokens.space,
        borderRadius: tokens.radius,
        boxShadow: tokens.shadow,
        maxWidth: tokens.container,
      },
    },
  };

  const body = `${banner("Tailwind preset")}/** @type {import('tailwindcss').Config} */\nmodule.exports = ${JSON.stringify(
    preset,
    null,
    2,
  )};\n`;
  writeFileSync(join(DIST, "tailwind.preset.cjs"), body);
}

// ─── Sanity checks ─────────────────────────────────────────────────────────
function verify() {
  const css = readFileSync(join(DIST, "tokens.css"), "utf8");
  if (!css.includes("--ua-red: #AB0520")) throw new Error("CSS: --ua-red missing");
  if (!css.includes("--az-red: var(--ua-red)")) throw new Error("CSS: --az-red alias missing");
  if (!css.includes("color-scheme: dark")) throw new Error("CSS: dark color-scheme missing");
  if (!css.includes("[data-theme=\"dark\"]")) throw new Error("CSS: dark selector missing");

  const scss = readFileSync(join(DIST, "tokens.scss"), "utf8");
  for (const v of ["$red", "$blue", "$bloom", "$chili", "$sky", "$oasis", "$azurite", "$midnight", "$cool-gray", "$warm-gray", "$leaf", "$river", "$mesa"]) {
    if (!scss.includes(`${v}: `)) throw new Error(`SCSS: ${v} missing`);
  }

  const ts = readFileSync(join(DIST, "tokens.ts"), "utf8");
  if (!ts.includes('"red": "#AB0520"')) throw new Error("TS: brand.red missing");

  const preset = require(join(DIST, "tailwind.preset.cjs"));
  if (preset.theme?.extend?.colors?.ua?.red !== "#AB0520") {
    throw new Error("Tailwind: colors.ua.red missing");
  }
}

emitCss();
emitScss();
emitTs();
emitTailwind();
verify();

console.log(`✓ Built @ua/ua-tokens v${tokens.version} → ${DIST}`);
console.log("  - dist/tokens.css");
console.log("  - dist/tokens.scss");
console.log("  - dist/tokens.ts");
console.log("  - dist/tokens.js");
console.log("  - dist/tokens.cjs");
console.log("  - dist/tokens.d.ts");
console.log("  - dist/tailwind.preset.cjs");
